[tool.poetry]
name = "repl_pygame_PBA-Jam"
version = "0.1.0"
description = ""
authors = ["eketsri1561 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pygame = "^2.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
